### ISSUE TITLE
Necessary to create a new HipChat user? What about other Token API?

### ISSUE THREAD

**Issue by Plasma** [parautenbach/TeamCity-HipChat-Notifier#13]
Hey,

In v1 of the HipChat API you can just create a "notify token" which has write-only access to the chat room, and can send as any arbitrary chat name you like.

I don't like the v2 HipChat API where you need a user token for a bot and it has read and write access.

I'm not familiar with the v2 API for HipChat that much, can you also support a "notify token" style system, ideally?

Cheers

**Comment by gregmac** [comment]
I'm also kinda bummed about this: the Teamcity notifications show up as if it was something I wrote. 

I was hoping this would be an improvement over using the tcWebHooks plugin, but at least with tcWebHooks the messages show up as coming from "Teamcity". I like customizing the messages and having different colors -- but I'm not sure this is a worthwhile trade-off right now.

----

Using a dedicated account for this is not awful, except I have several other integrations (all currently using v1 API).. if I have to pay for a separate user account for each, then it quickly starts to get very costly, so from that point of view I don't like dedicated user accounts as a solution. 

I could use a single account called something exciting like "Generic notifier" but I feel that is a step backwards: my current integrations have usernames like "JIRA", "Stash", "Teamcity", "Git", "Subversion", "Status monitoring" etc.

----

Honestly, this seems like a limitation in Hipchat's v2 API, and something Atlassian should address. 

Specifically, using the API key, it should be possible to send a notification with a different username.

Open request on Hipchat's forum: http://help.hipchat.com/forums/138883-suggestions-ideas/suggestions/6699126-need-from-column-for-api-v2-just-like-in-api-v1-it

**Comment by parautenbach** [comment]
Thank you @gregmac for the feedback. Let's hope Atlassian attends to this soon. I have voted for your request.
