### ISSUE TITLE
Support for Teamcity 9

### ISSUE THREAD

**Issue by j-martin** [parautenbach/TeamCity-HipChat-Notifier#44]
The plugin doesn't seem to be able to connect to the Hipchat server (or the failure happens earlier).
Using the "Test connection" button will give a "Connection failed!" message.

Note that we didn't try the plugin on Teamcity 8 since we upgraded all our servers. For the record, the main server is allowed to communicate with the hipchat api servers.

**Comment by parautenbach** [comment]
Hello Jean

Indeed, the plugin hasn't been built for TC 9 (yet). I just did a server upgrade during last week at work too, so I'm planning to make a new release very soon. 

(Technical note: The plugin uses some libraries already bundled with TC. The plugin hence has to use those versions to avoid reflection errors. Unfortunately, even between minor and bugfix TC releases, the Jetbrains team sometimes update these libraries too, and those could be major updates. That means the plugin needs to be recompiled.)

**Comment by parautenbach** [comment]
Something strange that I have just experienced: An existing OAuth token stopped working. I checked it in the admin console for the user (under API settings), and it was there. I think ran my unit tests for the plugin, and authorisation failed. I then created a quick test script with the same token, and it failed too, so that eliminates a problem with the plugin. After that, I recreated the token, and suddenly all is good. It seems like a problem on the HipChat API. Strange, I know, but perhaps that is your issue too (to no fault of yours). Are you using that particular account/token from any other places? Perhaps you could also try to reset/recreate the token.

**Comment by parautenbach** [comment]
You can test your current token as follows from a browser:

```
https://api.hipchat.com/v2/room?auth_token=TOKEN&auth_test=true
```

**Comment by j-martin** [comment]
Hey Pieter,

It seems every token that we ever generated from Hipchat is being rejected. I also created a new token with no success (both Notification and Admin). I am not doubting you got it working under Teamcity 9. Feel free to close this issue. Thanks for investigating.

```
{
error: {
code: 401,
message: "Invalid OAuth session",
type: "Unauthorized"
}
}
```

**Comment by parautenbach** [comment]
Hello, I tested with v0.8.0 of the plugin against TC 8.1.5.

**Comment by parautenbach** [comment]
Changed label to enhancement, to track this issue for upgrading the plugin to support TC 9.

**Comment by PaulHealey** [comment]
I get the same error as @j-martin trying the *Test Connection* button and when testing the token, as in *Invalid OAuth Session*. I created my token on the HipChat site via Group Admin / API page.

I notice you can go into a Room and create a token there as well, but that didn't seem to work either. The auth test gives a different error though:

```JSON
{
  error: {
    code: 403,
    message: "Only requests matching one of these authenticated principals are allowed to access this resource: an active user, a global add-on",
    type: "Forbidden"
  }
}
```

**Comment by macnibblet** [comment]
Any roadmap for teamcity 9 ?

**Comment by parautenbach** [comment]
Hi Antoine

Certainly! Due to a personal emergency I was offline and out of town for a while. It would hopefully not be too far from now. I'd say you can expect at least a compatibility update (i.e. no new features) in the next week or so.

**Comment by macnibblet** [comment]
You rock !

**Comment by jan0sch** [comment]
I'm currently running TeamCity 9.0.3 with the latest release and it works quite fine.

**Comment by parautenbach** [comment]
@macnibblet, the latest version, [v0.9.0](https://github.com/parautenbach/TeamCity-HipChat-Notifier/releases/tag/0.9.0) now supports TeamCity v9.0.2. :-)

@jan0sch, thanks for the feedback too: I think the issue would be that the plugin wouldn't always work reliably, or that some features won't work correctly. It very much depends on common dependencies between the plugin and TeamCity: The plugin uses some JARs already distributed with TeamCity. Sometimes these change, including API changes, even with minor releases, which can cause trouble. The other issue could be a TeamCity installation directory that isn't clean (e.g. an improper upgrade), where old JARs then live side-by-side with new ones, in which case the load order is [undefined](https://docs.oracle.com/javase/8/docs/technotes/tools/findingclasses.html).

**Comment by pbjorklund** [comment]
I'm getting "Connection failed" when running "Test connection" with TC 9.0.3 running on Windows Server 2012 R2

**Comment by parautenbach** [comment]
Hello, how did you generate the token? Did you create a v2 API personal access token? Have you checked that you can reach the HipChat servers from your TeamCity server (e.g. with a `telnet` test)?

**Comment by pbjorklund** [comment]
Ah, the README is not clear that you need to generate a personal token from https://xxxxxx.hipchat.com/account/api. When using that I get connection successful.
