### ISSUE TITLE
Getting "Connection failed!" with 0.8.0

### ISSUE THREAD

**Issue by Kizmar** [parautenbach/TeamCity-HipChat-Notifier#48]
I updated to TeamCity 8.1.5 (build 30240) and HipChat Notifier to 0.8.0. The exiting API token seemed to have stopped working, so I generated a new one, which also doesn't appear to be working.

The "Default room" field just says "(None)" and using "Test connection" results in a "Connection failed!" alert.

Is there something else I can/need to do to get this working again?

**Comment by Kizmar** [comment]
Uhg... just realized I was trying to use a room key instead of a person key. It works with a person key. Are there plans to support room notification keys?

**Comment by parautenbach** [comment]
Hi there

It seems like you have some environmental inconsistency. Did you upgrade your server recently? It actually seems (and this is a guess) that you have old JAR files (installed with TeamCity) somewhere and upon server startup these libraries get reflected, but it's not quite deterministic which JAR (if there are multiple versions of the same JAR). This was an [issue for others before](https://github.com/parautenbach/TeamCity-HipChat-Notifier/issues/42).

I have also experienced some [issues with keys](https://github.com/parautenbach/TeamCity-HipChat-Notifier/issues/44), but that was a consistent issue. 

Lastly, are you sure you are using a [HipChat API v2 key](https://www.hipchat.com/docs/apiv2)?

**Comment by parautenbach** [comment]
Hi there

Have you managed to resolve this in a permanent manner? I've release [v0.9.0](https://github.com/parautenbach/TeamCity-HipChat-Notifier/releases/tag/0.9.0) of the plugin, which supports TeamCity 9, in case you've upgraded too. In the mean time, I'm going to close this until there is more information. Feel free to re-open the issue.
