### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by chriskooken** [parautenbach/TeamCity-HipChat-Notifier#52]
I am trying to set this up against teamcity 9 and I get this error.

![screen shot 2015-05-19 at 4 13 35 pm](https://cloud.githubusercontent.com/assets/110292/7712895/19e42330-fe42-11e4-8cc9-915696d008f3.png)

My token is correct. What am I doing wrong?

**Comment by parautenbach** [comment]
It seems like you have a routing problem on your local network (inferred from the private subnet 192.168.0.0). Do you perhaps have a proxy in the way? On the TeamCity server, are you able to telnet to api.hipchat.com on port 80?

**Comment by chriskooken** [comment]
@parautenbach Thanks for the quick response! Yes. I just tried to telnet on the TeamCity host and it worked perfectly.

**Comment by parautenbach** [comment]
You're welcome!

I haven't seen this error before. I'm not sure why `api.hipchat.com` would resolve to `192.168.28.41`. 

Do you perhaps have any [https://confluence.jetbrains.com/display/TCD9/How+To...#HowTo...-ConfigureTeamCitytoUseProxyServerforOutgoingConnections](proxy settings) enabled?

**Comment by chriskooken** [comment]
It's not resolving to 192.168.28.41. That is the ip of the Teamcity host, and the URL in the browser. So the window is just saying the URL in the title. 

I have no proxy settings enabled.

**Comment by parautenbach** [comment]
Ah, yes, of course...

Would you mind explaining how you obtained the token?

Also try to enable [debug logging](https://github.com/parautenbach/TeamCity-HipChat-Notifier#developers) and post the logs here.

**Comment by chriskooken** [comment]
I obtained the token from here:

![screen shot 2015-05-19 at 5 14 59 pm](https://cloud.githubusercontent.com/assets/110292/7714190/9f0b0df0-fe4a-11e4-9fb6-ff3671533bb7.png)

**Comment by parautenbach** [comment]
Yes, I see... I'm still trying to resolve that issue with Atlassian. Somebody other than me created that setup, which incorrectly creates a v1 token. You need to log in to your HipChat console and create a v2 token.

**Comment by chriskooken** [comment]
I created 2 more tokens on the API page and neither of them work...

![screen shot 2015-05-19 at 5 23 29 pm](https://cloud.githubusercontent.com/assets/110292/7714341/cf16cb64-fe4b-11e4-92a8-2146fceef541.png)

**Comment by chriskooken** [comment]
Tried this too:

![screen shot 2015-05-19 at 5 25 54 pm](https://cloud.githubusercontent.com/assets/110292/7714388/262cef00-fe4c-11e4-8758-b0bb07e6f936.png)

**Comment by parautenbach** [comment]
Check the notice in your first screen shot: You're not creating a v2 API token. :-)

**Comment by chriskooken** [comment]
What about the second screenshot. That is correct, yes?

**Comment by chriskooken** [comment]
I figured it out. Thanks!

**Comment by parautenbach** [comment]
The second one seems to be a room only token, which won't work, as the plugin needs a token that can list all available rooms. Click on the "learn more" link in the first screen shot's notice.

**Comment by parautenbach** [comment]
Great!

**Comment by gh2k** [comment]
@chriskooken Could you let me know how you accomplished this? I had to install it with my personal token as I couldn't figure out a way to create a v2 integration token that wasn't room-only.

**Comment by chriskooken** [comment]
@gh2k You can't do that unfortunately. It has to be a room level.

**Comment by andrejohansson** [comment]
Hello, @parautenbach or @chriskooken could you please clarify this (with pictures for dummies)? 

I'm running v0.9.2 and I can't figure out how to generate v2 tokens. I've tried the "install integration", I've tried generating personal tokens at admin levels (which specifically says it's an v2 token) and also room tokens. Neither of these work, I just get "connection failed" when pressing the test button.

**Comment by parautenbach** [comment]
Go to https://DOMAIN.hipchat.com/account/api, where DOMAIN is your registered HipChat domain, and create a token there. I think the v1 API page actually warns you, and also provides a link to the v2 API pages. 

Btw, the "install integration" isn't something I created, and I'm still struggling to get the info out of Atlassian/HipChat in order to fix that. Whoever created that, configured it to use v1 API tokens.

**Comment by andrejohansson** [comment]
@parautenbach I go to that page, which type of token should I create? I have created all different scopes, including "Administer group". But still I get connection failed.

![2015-09-22 08_42_32-hipchat - your api access](https://cloud.githubusercontent.com/assets/2828428/10012213/e913542a-6105-11e5-81c5-fce99c3f48de.png)

**Comment by parautenbach** [comment]
I see things have changed quite a bit since I've been on that page. Quite hard to find it too...

Here are my settings:
* Administer Group (no idea why this one's required; must be a default HipChat applied when updating their API)
* Administer Room
* Manage Rooms
* Send Message
* Send Notification
* View Group (ditto)
* View Messages
* View Room

It's not clear which scope allows the listing of all rooms, but basically the plugin needs to:
* List all rooms
* Send a message/notification

**Comment by andrejohansson** [comment]
The two needed scopes seems to be:
* Send Notification
* View Room

My error was not ctrl+clicking multiple values.

**Comment by parautenbach** [comment]
Glad you got it going. I'll update the docs.

**Comment by squalsoft** [comment]
You need to select multiple scopes to have access
<img width="641" alt="2016-02-08 18 38 30" src="https://cloud.githubusercontent.com/assets/1629660/12890155/87bc7160-ce93-11e5-95d7-2e09c7d174b5.png">

**Comment by Ebeid** [comment]
Please help me get this working. I generated a room token
![hipchat room notification tokens](https://cloud.githubusercontent.com/assets/8538238/15436084/e86855e8-1e74-11e6-98dd-88162aec8862.png)

and used it on my TeamCity:

![hipchat notifier teamcity](https://cloud.githubusercontent.com/assets/8538238/15436085/e869b3d4-1e74-11e6-88d8-a4059cf73dfc.png)
