### ISSUE TITLE
${durationOfTests} is always 0

### ISSUE THREAD

**Issue by npaufler** [parautenbach/TeamCity-HipChat-Notifier#55]
After updating to 0.9.0, I tried to add the ${durationOfTests} macro to my Hipchat notifications. I'm finding that it is always returning 0 as the time period though, regardless  of the actual runtime of the job.

Thanks

**Comment by parautenbach** [comment]
Could you please send me the output of the log, after enabling [debug logging](https://github.com/parautenbach/TeamCity-HipChat-Notifier#developers)? This will show me the actual value provided by the build server.

**Comment by npaufler** [comment]
2015-07-10 18:53:52,720 - DEBUG - Adding standard build statistics
2015-07-10 18:53:52,721 - DEBUG -     Number of tests: 0
2015-07-10 18:53:52,721 - DEBUG -     Number of passed tests: 0
2015-07-10 18:53:52,722 - DEBUG -     Number of failed tests: 0
2015-07-10 18:53:52,722 - DEBUG -     Number of new failed tests: 0
2015-07-10 18:53:52,722 - DEBUG -     Number of ignored tests: 0
2015-07-10 18:53:52,722 - DEBUG -     Tests duration: 0
2015-07-10 18:53:52,722 - DEBUG - Adding discovered build statistics
2015-07-10 18:53:52,782 - DEBUG -
buildStageDuration:firstStepPreparation: 83.000000
2015-07-10 18:53:52,782 - DEBUG -     buildStageDuration:buildFinishing:
44.000000
2015-07-10 18:53:52,782 - DEBUG -
buildStageDuration:artifactsPublishing: 364.000000
2015-07-10 18:53:52,782 - DEBUG -     BuildDuration: 2368065
2015-07-10 18:53:52,782 - DEBUG -     buildStageDuration:sourcesUpdate:
12364.000000
2015-07-10 18:53:52,782 - DEBUG -
buildStageDuration:buildStepRUNNER_10: 2354766.000000
2015-07-10 18:53:52,782 - DEBUG -     BuildDurationNetTime: 2368032

Would be the relevant bit, I believe.

All of my build steps are commandline. Perhaps that's the issue? Would
there be any way to expose the BuildDurationNetTime in the same way
DurationOfTests is?

Thanks


On Thu, Jul 9, 2015 at 2:51 PM, Pieter Rautenbach <notifications@github.com>
wrote:

> Could you please send me the output of the log, after enabling debug
> logging
> <https://github.com/parautenbach/TeamCity-HipChat-Notifier#developers>?
> This will show me the actual value provided by the build server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parautenbach/TeamCity-HipChat-Notifier/issues/55#issuecomment-120140777>
> .
>



-- 
Nicholas Paufler
System Administrator
Clio - Practice Management Simplified
1-888-858-2546 nicholas.paufler@clio.com
www.clio.com | blog <http://www.clio.com/blog> | twitter
<http://www.twitter.com/goclio> | facebook <http://www.facebook.com/goclio>

**Comment by npaufler** [comment]
Happy to provide any additional info you need.

**Comment by parautenbach** [comment]
Which version of TeamCity are you running? I'm unable to reproduce this with plugin v0.9.0 and TeamCity v9.0.2 (build 32195).

Template:
```
Build <a href="${serverUrl}/viewType.html?buildTypeId=${buildTypeId}">${fullName}</a> <#if hasBranch>on branch <b>${branch}</b></#if> was successful. It was build number <a href="${serverUrl}/viewLog.html?buildId=${buildId}">#${buildNumber}</a> and was triggered by ${triggeredBy} (${durationOfTests}). <#if hasContributors>Contributors: ${contributors}.</#if> <img src="${emoticonUrl}">
```

Log:
```
2015-08-02 18:17:35,189 - DEBUG - Adding standard build statistics 
2015-08-02 18:17:35,190 - DEBUG - 	Number of tests: 0 
2015-08-02 18:17:35,190 - DEBUG - 	Number of passed tests: 0 
2015-08-02 18:17:35,190 - DEBUG - 	Number of failed tests: 0 
2015-08-02 18:17:35,190 - DEBUG - 	Number of new failed tests: 0 
2015-08-02 18:17:35,190 - DEBUG - 	Number of ignored tests: 0 
2015-08-02 18:17:35,190 - DEBUG - 	Tests duration: 0 
```

Result:
![screen shot 2015-08-02 at 18 19 36](https://cloud.githubusercontent.com/assets/743320/9026964/265ba110-3943-11e5-9e50-72bb1f7db52e.png)

**Comment by parautenbach** [comment]
This seems to be a bug with the TeamCity Open API (in specifically TC v0.9.0). This is how the build duration value is added to the template:

```java
BuildStatistics statistics = build.getFullStatistics();
...
templateMap.put(HipChatNotificationMessageTemplates.Parameters.DURATION_OF_TESTS, statistics.getTotalDuration());
```

where `BuildStatistics` is defined by the [API](http://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/BuildStatistics.html#getTotalDuration()).

This isn't well documented, but there is an alternative: All build statistics found by the plugin are available to the templates using a `stats.` prefix. E.g., this template works:

```
Build <a href="${serverUrl}/viewType.html?buildTypeId=${buildTypeId}">${fullName}</a> <#if hasBranch>on branch <b>${branch}</b></#if> was successful. It was build number <a href="${serverUrl}/viewLog.html?buildId=${buildId}">#${buildNumber}</a> and was triggered by ${triggeredBy} (duration: ${.data_model["stats.BuildDuration"] / 1000}s). <#if hasContributors>Contributors: ${contributors}.</#if> <img src="${emoticonUrl}">
```

![screen shot 2015-08-02 at 18 45 31](https://cloud.githubusercontent.com/assets/743320/9027068/b0a68cb0-3946-11e5-9f25-5b3697932254.png)

**Comment by npaufler** [comment]
Confirmed, that does what we need. Thank you kindly.

**Comment by parautenbach** [comment]
You're welcome.
