### ISSUE TITLE
Installation Issue - Failed to Initialize Spring Context

### ISSUE THREAD

**Issue by NikSouthworth** [parautenbach/TeamCity-HipChat-Notifier#57]
Hey,

Am attempting to install v0.9.1 on TeamCity v9.0.4 Server but am getting the following error:

[2015-08-05 11:06:45,281]  ERROR - gins.spring.SpringPluginLoader - Failed to initialize spring context for plugin HipChat Notifier

Any ideas what I am doing wrong? :)

Thanks.

**Comment by parautenbach** [comment]
It's probably a change in dependencies also used by the plugin. I'll have a look.

**Comment by parautenbach** [comment]
Could you confirm your TC version please?

**Comment by parautenbach** [comment]
This is most likely a duplicate of #58.

**Comment by parautenbach** [comment]
Fixed in [v0.9.2](https://github.com/parautenbach/TeamCity-HipChat-Notifier/releases/tag/0.9.2).
