### ISSUE TITLE
Confused about which token is required

### ISSUE THREAD

**Issue by ScottSingleton** [parautenbach/TeamCity-HipChat-Notifier#65]
The docs aren't clear as to which token type is required nor the correct api URL.

I've tried many different combinations and have not once been able to get a successful test connection.

**Comment by parautenbach** [comment]
Kindly refer to #52 (and #62). You need a personal token (tied to a user account) for the v2 API, with the correct admin scopes. 

The default API URL is correct, so don't adjust that in the configuration unless you're sending notifications to your own HipChat server.

**Comment by parautenbach** [comment]
If you could explain one specific route you followed, and the values you entered (without posting your token, for your own safety) I would be able to help better.

**Comment by ScottSingleton** [comment]
Thanks for your help;   It was the admin rights that tricked me up.  I saw a note at the bottom of #62 that listed two lesser privileged rights and had been trying those with the user token.  

This of course was after trying to get the token provided by Atlassian :/

After seeing your first note here I issued a token with ALL rights then worked backwards from there.  Thank you so much.
