### ISSUE TITLE
After saving changes in TeamCity 8.x, page is blank

### ISSUE THREAD

**Issue by kenny-evitt** [parautenbach/TeamCity-HipChat-Notifier#71]
I just installed the latest version of the plugin. The TeamCity version is 8.0.6 (build 27767). TeamCity is running on Windows Server 2008 x64.

Any changes I make _are_ saved.

**Comment by parautenbach** [comment]
Are you running TC behind a [proxy](https://github.com/parautenbach/TeamCity-HipChat-Notifier#troubleshooting)?

**Comment by kenny-evitt** [comment]
@parautenbach Nope

**Comment by parautenbach** [comment]
No further information provided.
