### ISSUE TITLE
TeamCity 9.1.6 seems to have killed the Notifier

### ISSUE THREAD

**Issue by jbwise** [parautenbach/TeamCity-HipChat-Notifier#73]
We upgraded to TeamCity 9.1.6 when it came out on 29JAN, and it appears to have killed the integration.  We've reinstalled, restarted, and recreated API keys, but to no avail.  When clicking the test button, we get a 400 error from configureHipChat.html.  None of the room lists are populated anymore and no messages get to HipChat.

Thanks!

**Comment by andreiverdes** [comment]
+1

**Comment by squalsoft** [comment]
I have 9.1.6 and it works great.

**Comment by parautenbach** [comment]
@jbwise, I will try and test over the weekend, but if it works for @squalsoft, then my guess would be that perhaps you didn't clean out all the working directories when you upgraded your TC installation. If any JAR files from a prior version remains, there is a chance of an ambiguity. Perhaps you could both just confirm which version of the plugin you use? Maybe you use the same TC version, but different versions of the plugin.

**Comment by andreiverdes** [comment]
I'm using a fresh TeamCity Professional 9.1.6 (build 37459) and the latest plugin version  0.9.2 - 1fdd36c. Today I'll try to enable debugging and see the logs.

**Comment by andreiverdes** [comment]
Ok...so apparently something's going on...
Workaround:
1. Define an v2 API token with scope `View Rooms` or `View Groups`
2. Use that to configure `Administration -> Hipchat`notifier
3. Go to `Projects -> <Sub project> -> Hipchat` tab and select your room
4. Now, when the plugin will try sending notifications it will result with hipchat api error 403
5. Define a new v2 API token with Scope `Send Notifications` 
6. Go to `Administration -> Hipchat` notifier again, and use the `Send Notifications` scope token
7. Save
8. Run your configurations, it should work now, the plugin can successfully send notifications

Observations:
Test Connection from `Administration -> HipChat` notifier is successful only using a token with `View Rooms` or `View Groups` token
A `View Rooms` or a `View Groups` token will result in 403 when the plugin will try to actually post something.
I'll post more details tomorrow... I hope this is a temporary fix until I understand the token scopes in hipchat API and why, for example an `Administer Group` scope can't be used to get the rooms and post in them as well.

**Comment by jbwise** [comment]
I hate to admit it, but our error could have been a simple expired token.  I just saw the expiration date on the original token was Jan 30, 2016.  The new tokens I created did not have the three permissions you listed above, but when I created a token with Send Message, Send Notification, View Room, View Messages, and View Group, the plugin works as expected.

It seems this isn't a bug with either the plugin or the new release, just poor timing of an expiration date and an update.  It might be nice to specify in the plugin which permissions are required to work appropriately in the API key.

Thanks, andreiverdes!

**Comment by andreiverdes** [comment]
Glad to hear that!

**Comment by gsvitak** [comment]
@andreiverdes I had the same problem with a brand new install. I used your suggestion of creating the token with View Groups and everything started working.

**Comment by baqueiro** [comment]
thankyou @andreiverdes

**Comment by dragon788** [comment]
Thanks for the tip. You can actually give out multiple permissions to an API key in HipChat, just hold Ctrl while selecting (probably Command on Mac). I gave `Send Message, Send Notification, View Group, View Room` and it is working great now.

**Comment by andreiverdes** [comment]
Cool @dragon788! Thanks! I would've never thought about this :D
