### ISSUE TITLE
Can't include artifacts' names in a message.

### ISSUE THREAD

**Issue by bratfizyk** [parautenbach/TeamCity-HipChat-Notifier#74]
I might be wrong, but I can't see any way to include information about produced artifacts in a message that gets sent to HipChat.

As a basic version it would be nice just to be able to list all the produced artifacts.

In an ideal world it would be great to apply some filtering and artifacts' names operation.

**Comment by parautenbach** [comment]
Hello, have a look at #54.

**Comment by parautenbach** [comment]
No reply. Please reopen if unresolved.
